server:
  port: 8088
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/polling_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: poller
    password: poller
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
polling:
  fixedRate: 600000 # 10 minutes
  connection:
    timeout: 1000